[tool.poetry]
name = "lqts"
version = "1.0.54"
description = ""
authors = ["Bradley L Campbell <bradley.campbell@navy.mil>"]
include = ["lqts/version.py"]

[tool.poetry.scripts]
qsub = "lqts.commands.qsub:qsub"
qsub-multi = "lqts.commands.qsub:qsub_multi"
qsub-cmulti = "lqts.commands.qsub:qsub_cmulti"
qsub-argfile = "lqts.commands.qsub:qsub_argfile"
qsub-test = "lqts.commands.qsub:qsub_test"
qstart = "lqts.commands.qstart:qstart"
qstat = "lqts.commands.qstat:qstat"
qclear = "lqts.commands.qclear:qclear"
qdel = "lqts.commands.qdel:qdel"
qworkers = "lqts.commands.qworkers:qworkers"
qwait = "lqts.commands.qwait:qwait"
qsummary = "lqts.commands.qsummary:qsummary"
qpriority = "lqts.commands.qpriority:qpriority"

[tool.poetry.dependencies]
python = "^3.10"
# fastapi = "0.78.0"
click = "7.1.2"
# Jinja2 = "3.1.2"
psutil = "5.9.1"
# pydantic = "1.9.1"
requests = "2.31.0"
# starlette = "0.19.1"
tqdm = "4.64.0"
ujson = "5.4.0"
urllib3 = "1.26.9"
uvicorn = "0.17.6"
fastapi = "0.95.1"
starlette = "0.26.1"
pydantic = "1.10.7"
jinja2 = "^3.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.10.1"
sphinx = "^5.0.2"
sphinx-pydantic = ">=0.1.1"
m2r = "^0.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
